apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashcorr-cv
  namespace: plex-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
        image: plexinc/pms-docker:latest
        imagePullPolicy: Always
        name: plex-server
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30